### ISSUE TITLE
vmw_backdoor can't be cross-compiled on a non-x86_64 host

### ISSUE THREAD

**Issue by bcressey** [coreos/vmw_backdoor-rs#11]
First of all, thanks for making this crate! It's fantastic. We're using it in our own cloud-init replacement in Bottlerocket.

We ran into https://github.com/bottlerocket-os/bottlerocket/issues/1484 today and I wanted to get your thoughts on a potential fix.

The build script has this conditional:
```
fn main() {
    #[cfg(all(target_os = "linux", target_arch = "x86_64"))]
    asm_x86_64_linux();
}
```

However, since build scripts are compiled for the host, this effectively turns the script into a no-op when built on a non-x86_64 architecture. When the build script is run later, even if `--target` and `TARGET_CC` are set correctly, the script will not compile the x86_64 assembly. Crates that make use of those symbols will then fail to link properly.

To fix cross-compiling, it's sufficient to remove that `cfg` directive from the build script. I'm not entirely sure what impact this would have on downstream crates. For the most part, I expect they would need to use similar conditionals to avoid the crate dependency and to prevent calling into the functions backed by the assembly.

**Comment by lucab** [comment]
Thanks for the report. Unfortunately I never had to deal with cross-compiling crates, so I don't have much first-hand knowledge on this.

So far the only other consumer of this library (to my knowledge) is https://github.com/coreos/afterburn, so as long as we fix that one we can freely tweak the build script here in order to properly cross-compile.

The reason behind the build-script condition is that on other arches (e.g. ppc64le) the ASM fragments can't be built by the native compiler. So I guess just removing the `cfg` won't directly work, unless `vmw_backdoor` is always only declared as a conditional dependency (which maybe the docs here should really recommend?).

Looking at [build scripts docs](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts), I have a feeling that env variables should be used instead of the current `cfg` line, in order to achieve the original goal.
Can you check whether the following works for you?
```rust
fn main() {
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH")
        .expect("missing $CARGO_CFG_TARGET_ARCH env variable");
    let target_os =
        std::env::var("CARGO_CFG_TARGET_OS").expect("missing $CARGO_CFG_TARGET_OS env variable");
    if target_arch == "x86_64" && target_os == "linux" {
        asm_x86_64_linux();
    };
}

```

**Comment by bcressey** [comment]
Yup, that works for me, thanks!

Here's a [test case](https://gist.github.com/bcressey/8f7ae28d34f8e39045a03cc9cc543d50) if you have access to an arm64 system. It's not particularly minimal because it requires a glibc build and install.

There's a different problem where musl builds fail for this reason:
```
error[E0425]: cannot find function `iopl` in crate `libc`
   --> /tmp/vmw_backdoor-rs/src/backdoor.rs:101:34
    |
101 |         let err = unsafe { libc::iopl(level) };
    |                                  ^^^^ not found in `libc`
```

That's more of a deficiency in Rust's libc crate, though; `iopl` seems to be [special-cased for x86_64 gnu](https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/gnu/b64/x86_64/mod.rs#L846).

If you wanted to guard against that, you could also check that `CARGO_CFG_TARGET_ENV` was "gnu". But then you'd have to revisit the build script if `libc` changed, which doesn't seem ideal. It would also obscure the actual problem - musl builds would fail with the symbol errors at link time after the assembly was quietly skipped. The compile error seems much clearer.

**Comment by lucab** [comment]
The latter looks like a matter of adding libc-rs binding for `iopl` on musl, and then the fix should be automatically picked up here once a new version of libc-rs with the fix is released.
If my reading of this is correct, I'd rather not special-case it here.
